cp kernel.py C://Program FIles/CariboSystem/
cp core.py C://Program Files/CariboSystem
cp calc.py C://Program Files/CariboSystem
cp switch.py C://Program Files/CariboSystem
cp switch2.py C://Program Files/CariboSystem
cp help.py C://Program Files/CariboSystem
cp boot.py C://Program Files/CariboSystem
cp bsod.py C://Program Files/CariboSystem
cp info.py C://Program Files/CariboSystem
cp os_info.py C://Program Files/CariboSystem
cp login.py C://Program Files/CariboSystem
cp start.bat C://Program Files/CariboSystem
cp uninstall.bat C://Program Files/CariboSystem
cp message.py C://Program Files/CariboSystem
cp thanks.py C://Program Files/CariboSystem
