 rm C://Program Files/CariboSystem/kernel.py
 rm C://Program Files/CariboSystem/core.py
 rm C://Program Files/CariboSystem/calc.py
 rm C://Program Files/CariboSystem/switch.py
 rm C://Program Files/CariboSystem/switch2.py 
 rm C://Program Files/CariboSystem/help.py 
 rm C://Program Files/CariboSystem/boot.py 
 rm C://Program Files/CariboSystem/bsod.py 
 rm C://Program Files/CariboSystem/info.py 
 rm C://Program Files/CariboSystem/os_info.py
 rm C://Program Files/CariboSystem/login.py
 rm C://Program Files/CariboSystem/start.sh
 rm C://Program Files/CariboSystem/message.py
 rm C://Program Files/CariboSystem/thanks.py
